// GENERATED by build_icons.py. Tool registry: key -> display label + names to auto-icon in text.
const TOOLS = {
 "python": {
  "label": "Python",
  "aliases": [
   "Python"
  ]
 },
 "java": {
  "label": "Java",
  "aliases": [
   "Java"
  ]
 },
 "javascript": {
  "label": "JavaScript",
  "aliases": [
   "JavaScript"
  ]
 },
 "c": {
  "label": "C",
  "aliases": []
 },
 "sql": {
  "label": "SQL",
  "aliases": [
   "SQL"
  ]
 },
 "systemverilog": {
  "label": "SystemVerilog",
  "aliases": [
   "SystemVerilog"
  ]
 },
 "html": {
  "label": "HTML",
  "aliases": [
   "HTML"
  ]
 },
 "css": {
  "label": "CSS",
  "aliases": [
   "CSS"
  ]
 },
 "latex": {
  "label": "LaTeX",
  "aliases": [
   "LaTeX"
  ]
 },
 "racket": {
  "label": "Racket",
  "aliases": [
   "Racket"
  ]
 },
 "aws": {
  "label": "AWS",
  "aliases": [
   "AWS"
  ]
 },
 "terraform": {
  "label": "Terraform",
  "aliases": [
   "Terraform"
  ]
 },
 "gcp": {
  "label": "GCP",
  "aliases": [
   "GCP"
  ]
 },
 "docker": {
  "label": "Docker",
  "aliases": [
   "Docker Compose",
   "Docker"
  ]
 },
 "git": {
  "label": "Git",
  "aliases": [
   "Git"
  ]
 },
 "github": {
  "label": "GitHub",
  "aliases": [
   "GitHub"
  ]
 },
 "copilot": {
  "label": "GitHub Copilot",
  "aliases": [
   "GitHub Copilot"
  ]
 },
 "agile": {
  "label": "Agile / Scrum",
  "aliases": [
   "Agile/Scrum",
   "Agile"
  ]
 },
 "whisper": {
  "label": "Whisper",
  "aliases": [
   "Whisper"
  ]
 },
 "groq": {
  "label": "Groq API",
  "aliases": [
   "Groq API",
   "Groq"
  ]
 },
 "bm25": {
  "label": "BM25",
  "aliases": [
   "BM25"
  ]
 },
 "nocodb": {
  "label": "NocoDB",
  "aliases": [
   "NocoDB"
  ]
 },
 "caddy": {
  "label": "Caddy",
  "aliases": [
   "Caddy"
  ]
 },
 "playwright": {
  "label": "Playwright",
  "aliases": [
   "Playwright"
  ]
 },
 "pycryptodome": {
  "label": "PyCryptodome",
  "aliases": [
   "PyCryptodome"
  ]
 },
 "sockets": {
  "label": "Sockets",
  "aliases": [
   "Sockets"
  ]
 },
 "aes": {
  "label": "AES-256-GCM",
  "aliases": [
   "AES-256-GCM"
  ]
 },
 "d3": {
  "label": "D3.js",
  "aliases": [
   "D3.js"
  ]
 },
 "leaflet": {
  "label": "Leaflet.js",
  "aliases": [
   "Leaflet.js"
  ]
 },
 "react": {
  "label": "React",
  "aliases": [
   "React"
  ]
 },
 "vite": {
  "label": "Vite",
  "aliases": [
   "Vite"
  ]
 },
 "tailwind": {
  "label": "Tailwind CSS",
  "aliases": [
   "Tailwind CSS",
   "Tailwind"
  ]
 },
 "zustand": {
  "label": "Zustand",
  "aliases": [
   "Zustand"
  ]
 },
 "supabase": {
  "label": "Supabase",
  "aliases": [
   "Supabase"
  ]
 },
 "postgres": {
  "label": "PostgreSQL",
  "aliases": [
   "PostgreSQL"
  ]
 },
 "riscv": {
  "label": "RISC-V",
  "aliases": [
   "RISC-V"
  ]
 },
 "fpga": {
  "label": "FPGA",
  "aliases": [
   "FPGA"
  ]
 },
 "ecp5": {
  "label": "ECP5",
  "aliases": [
   "ECP5"
  ]
 },
 "yosys": {
  "label": "Yosys",
  "aliases": [
   "Yosys"
  ]
 },
 "windows": {
  "label": "Windows",
  "aliases": [
   "Windows"
  ]
 },
 "r": {
  "label": "R",
  "aliases": []
 },
 "rstudio": {
  "label": "RStudio",
  "aliases": [
   "RStudio"
  ]
 },
 "datacleaning": {
  "label": "Data cleaning",
  "aliases": []
 },
 "realtime": {
  "label": "Real-Time Systems",
  "aliases": []
 },
 "schedulability": {
  "label": "Schedulability Analysis",
  "aliases": []
 }
};
